Import potrzebnych bibliotek oraz sprawdzenie czy mamy poprawnie skonfigurowane środowisko

In [10]:
import torch
#import numpy as np
#import matplotlib.pyplot as plt
#import pandas as pd

print(torch.__version__)    # Sprawdzenie wersji PyTorch
torch.cuda.is_available()   # Sprawdzenie czy jest dostępna karta graficzna

2.0.1+cu118


True

Zapisanie wartości skalarnej

In [15]:
scalar = torch.tensor(3.1415)
print(scalar)        # Wyświetlenie wartości tensora
print(scalar.dtype)  # Wyświetlenie typu tensora
print(scalar.shape)  # Wyświetlenie rozmiaru tensora
print(scalar.ndim)   # Wyświetlenie liczby wymiarów tensora (ilość nawiasów kwadratowych)
scalar.item()        # Wyświetlenie wartości tensora jako liczby

tensor(3.1415)
torch.float32
torch.Size([])
0


3.1414999961853027

Zapisanie wektora

In [17]:
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)       # Wyświetlenie wartości tensora
print(vector.dtype) # Wyświetlenie typu tensora
print(vector.shape) # Wyświetlenie rozmiaru tensora (5 razy jeden element)
print(vector.ndim)  # Wyświetlenie liczby wymiarów tensora

tensor([1, 2, 3, 4, 5])
torch.int64
torch.Size([5])
1


Zapisanie macierzy

In [18]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(MATRIX)       # Wyświetlenie wartości tensora
print(MATRIX.dtype) # Wyświetlenie typu tensora
print(MATRIX.shape) # Wyświetlenie rozmiaru tensora (2 razy 3 elementy)
print(MATRIX.ndim)  # Wyświetlenie liczby wymiarów tensora

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])
2


Zapis tensora

In [26]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(TENSOR)       # Wyświetlenie wartości tensora
print(TENSOR.dtype) # Wyświetlenie typu tensora
print(TENSOR.shape) # Wyświetlenie rozmiaru tensora (2 razy 2 wiersze po 3 elementy)
print(TENSOR.ndim)  # Wyświetlenie liczby wymiarów tensora
print(TENSOR[0, 1, 2])
print(TENSOR[1])

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [0, 1, 2]]])
torch.int64
torch.Size([2, 2, 3])
3
tensor(6)
tensor([[7, 8, 9],
        [0, 1, 2]])


![Alt text](image0.1.png)
Źródło: https://www.learnpytorch.io/00_pytorch_fundamentals/