Import potrzebnych bibliotek oraz sprawdzenie czy mamy poprawnie skonfigurowane środowisko

In [2]:
import torch
#import numpy as np
#import matplotlib.pyplot as plt
#import pandas as pd

print(torch.__version__)    # Sprawdzenie wersji PyTorch
torch.cuda.is_available()   # Sprawdzenie czy jest dostępna karta graficzna

2.0.1+cu118


True

## Zapisanie wartości skalarnej

In [15]:
scalar = torch.tensor(3.1415)
print(scalar)        # Wyświetlenie wartości tensora
print(scalar.dtype)  # Wyświetlenie typu tensora
print(scalar.shape)  # Wyświetlenie rozmiaru tensora
print(scalar.ndim)   # Wyświetlenie liczby wymiarów tensora (ilość nawiasów kwadratowych)
scalar.item()        # Wyświetlenie wartości tensora jako liczby

tensor(3.1415)
torch.float32
torch.Size([])
0


3.1414999961853027

## Zapisanie wektora

In [17]:
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)       # Wyświetlenie wartości tensora
print(vector.dtype) # Wyświetlenie typu tensora
print(vector.shape) # Wyświetlenie rozmiaru tensora (5 razy jeden element)
print(vector.ndim)  # Wyświetlenie liczby wymiarów tensora

tensor([1, 2, 3, 4, 5])
torch.int64
torch.Size([5])
1


## Zapisanie macierzy

In [18]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(MATRIX)       # Wyświetlenie wartości tensora
print(MATRIX.dtype) # Wyświetlenie typu tensora
print(MATRIX.shape) # Wyświetlenie rozmiaru tensora (2 razy 3 elementy)
print(MATRIX.ndim)  # Wyświetlenie liczby wymiarów tensora

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])
2


## Zapis tensora

In [26]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(TENSOR)       # Wyświetlenie wartości tensora
print(TENSOR.dtype) # Wyświetlenie typu tensora
print(TENSOR.shape) # Wyświetlenie rozmiaru tensora (2 razy 2 wiersze po 3 elementy)
print(TENSOR.ndim)  # Wyświetlenie liczby wymiarów tensora
print(TENSOR[0, 1, 2])
print(TENSOR[1])

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [0, 1, 2]]])
torch.int64
torch.Size([2, 2, 3])
3
tensor(6)
tensor([[7, 8, 9],
        [0, 1, 2]])


![Alt text](image0.1.png)
Źródło: https://www.learnpytorch.io/00_pytorch_fundamentals/

# Tensory generowane losowo

Większość etapów nauki sieci neuronowej zaczyna się od stworzenia tensora z wartościami losowymi, które następnie są modyfikowane w celu lepszej reprezentacji danych.

In [7]:
random_tensor = torch.rand(2, 2, 3, 3)
print(random_tensor)

tensor([[[[0.5264, 0.9622, 0.7175],
          [0.3197, 0.5637, 0.4880],
          [0.4932, 0.5586, 0.9850]],

         [[0.9570, 0.5907, 0.3195],
          [0.4696, 0.4603, 0.5166],
          [0.7343, 0.1441, 0.3717]]],


        [[[0.5691, 0.4958, 0.8530],
          [0.4482, 0.7124, 0.3810],
          [0.8843, 0.8851, 0.7419]],

         [[0.9179, 0.6624, 0.7498],
          [0.0464, 0.0931, 0.4399],
          [0.9713, 0.9617, 0.0300]]]])


In [10]:
print(random_tensor[0, 1, 2, 2])
print(random_tensor.ndim)

tensor(0.3717)
4


## Tworzenie tensora odpowiadającemu obrazowi

In [11]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # 3 kanały(R, G, B) i obraz o rozmiarze 224x224
print(random_image_size_tensor)
print(random_image_size_tensor.ndim)
print(random_image_size_tensor.shape)

tensor([[[0.4023, 0.9960, 0.1962,  ..., 0.3941, 0.8797, 0.6221],
         [0.9318, 0.8165, 0.7934,  ..., 0.4217, 0.4254, 0.7884],
         [0.4508, 0.1750, 0.7910,  ..., 0.1129, 0.1015, 0.1879],
         ...,
         [0.5657, 0.6546, 0.7308,  ..., 0.1684, 0.2551, 0.6381],
         [0.3703, 0.0750, 0.6826,  ..., 0.9056, 0.5517, 0.5703],
         [0.1917, 0.1759, 0.5944,  ..., 0.8711, 0.4642, 0.2398]],

        [[0.3479, 0.1902, 0.2426,  ..., 0.8201, 0.7069, 0.5479],
         [0.5310, 0.0180, 0.0139,  ..., 0.6427, 0.2866, 0.1931],
         [0.4884, 0.3727, 0.6409,  ..., 0.8585, 0.9155, 0.4308],
         ...,
         [0.3723, 0.2577, 0.2177,  ..., 0.4448, 0.5500, 0.8978],
         [0.0910, 0.1726, 0.6137,  ..., 0.4448, 0.9486, 0.7507],
         [0.5713, 0.0358, 0.3805,  ..., 0.4824, 0.8983, 0.5171]],

        [[0.1839, 0.7027, 0.0906,  ..., 0.7012, 0.6948, 0.6033],
         [0.8747, 0.5921, 0.2764,  ..., 0.2504, 0.9608, 0.3137],
         [0.9207, 0.8350, 0.6614,  ..., 0.7596, 0.6908, 0.

## Tworzenie tensorów wypełnionych zerami lub jedynkami

In [12]:
zeros = torch.zeros((3, 3))
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
ones = torch.ones((3, 3))
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## Tworzenie tensorów w danym zakresie

In [14]:
range = torch.arange(start=0, end=6, step=1) # Utworzenie zakresu od 0 do 5 z krokiem 1
print(range)

tensor([0, 1, 2, 3, 4])


## Jeśli chcemy utworzyć tensor o takich samych wymiarach JAK inny, ale z innymi danymi

In [16]:
five_zeros = torch.zeros_like(input=range) # Utworzenie tensora wypełnionego zerami o rozmiarze takim jak w range
print(five_zeros)

tensor([0, 0, 0, 0, 0])


# Typy danych wykorzystywanych w tensorach

Częste problemy z pracą na tensorach:
1. Nie znajdują się na tym samym urządzeniu
2. Tensory są różnych rozmiarów
3. Nie mają spójnych typów danych (np. float16 i float32)

In [21]:
float_32_tensor = torch.tensor([1, 2, 3], 
                               dtype=torch.float32,           # Ustawienie typu tensora na float32
                               device=torch.device("cuda:0"), # Ustawienie urządzenia na GPU (cuda:0) lub CPU (cpu)
                               requires_grad=False)           # Ustawienie czy tensor ma wymagać gradientu
print(float_32_tensor)

tensor([1., 2., 3.], device='cuda:0')


Zmiana typu danych używanych w tensorze

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16) # Konwersja tensora na float16
print(float_16_tensor)

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)


# Operacje na tensorach

In [ ]:
tensor = torch.tensor([1, 2, 3])

Dodawanie

In [29]:
print(tensor + 10) # Dodanie 10 do każdego elementu tensora
print(torch.add(tensor, 10)) # Dodanie 10 do każdego elementu tensora

tensor([11, 12, 13])
tensor([11, 12, 13])


Mnożenie

In [27]:
print(tensor * 10) # Pomnożenie każdego elementu tensora przez 10
print(torch.multiply(tensor, 10)) # Pomnożenie każdego elementu tensora przez 10

tensor([10, 20, 30])
tensor([10, 20, 30])


Odejmowanie

In [30]:
print(tensor - 10) # Odjęcie 10 od każdego elementu tensora
print(torch.subtract(tensor, 10)) # Odjęcie 10 od każdego elementu tensora

tensor([-9, -8, -7])
tensor([-9, -8, -7])


Możenie każdego elementu tensora przez siebie

In [32]:
print(tensor, "*", tensor)
print(tensor * tensor) # Pomnożenie każdego elementu tensora przez siebie

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


Mnożenie macierzowe
![Alt text](image0.2.png)
Źródło: https://www.mathsisfun.com/algebra/matrix-multiplying.html
Istnieją 2 zasady:
1. Wymiary wewnętzne macierzy muszą być takie same          (1,2) @ (2, 3) będzie ok.    
2. Rozmiar macierzy wynikowej jest wymiarami zewnętrznymi   (1,2) @ (2, 3) będzie (1, 3)

In [42]:
print(torch.matmul(tensor, tensor)) # Mnożenie macierzowe tensora przez siebie
print(tensor @ tensor) # Mnożenie macierzowe tensora przez siebie

tensor(14)


In [44]:
x = torch.rand(1, 2)
y = torch.rand(2, 3)
print(x, "\n", y)
print(x @ y) # Mnożenie macierzowe dwóch tensorów

tensor([[0.7453, 0.4441]]) 
 tensor([[0.3432, 0.4797, 0.6493],
        [0.6150, 0.5726, 0.8034]])
tensor([[0.5289, 0.6118, 0.8407]])


Transpozycja

In [49]:
basic_tensor = torch.tensor([[1, 2],
                            [3, 4],
                            [5, 6]])
print(basic_tensor, basic_tensor.shape) # Wyświetlenie tensora i jego rozmiaru
print(basic_tensor.T, basic_tensor.T.shape) # Transpozycja tensora i wyświetlenie jego rozmiaru

tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])
tensor([[1, 3, 5],
        [2, 4, 6]]) torch.Size([2, 3])


# Funkcje do zastosowania na tensorach

In [50]:
x_tensor = torch.arange(0, 100, 10)
print(x_tensor)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [62]:
print(torch.min(x_tensor)) # Znalezienie najmniejszej wartości w tensorze
print(x_tensor.min()) # Znalezienie najmniejszej wartości w tensorze (inny sposób)
print(x_tensor.argmin()) # Znalezienie indeksu najmniejszej wartości w tensorze

print(torch.max(x_tensor)) # Znalezienie największej wartości w tensorze
print(x_tensor.max()) # Znalezienie największej wartości w tensorze (inny sposób)
print(x_tensor.argmax()) # Znalezienie indeksu największej wartości w tensorze

tensor(0)
tensor(0)
tensor(0)
tensor(90)
tensor(90)
tensor(9)


In [58]:
print(torch.mean(x_tensor.type(torch.float32))) # Znalezienie średniej wartości w tensorze
print(x_tensor.type(torch.float32).mean()) # Znalezienie średniej wartości w tensorze (inny sposób)
# Warto zaznaczyć, że funkcja mean() wymaga typu float32, dlatego należy dokonać konwersji z typu long

tensor(45.)
tensor(45.)


In [59]:
print(torch.sum(x_tensor)) # Znalezienie sumy wartości w tensorze
print(x_tensor.sum()) # Znalezienie sumy wartości w tensorze (inny sposób)

tensor(450)
tensor(450)


# Zaawansowane funkcje tensorów

- Reshape - zmienia kształt tensora do wskazanego
- View - zwraca widok tensora wejściowego o wskazanym kształcie, ale z zachowaniem danych oryginalnego tensora
- Stacking - łączenie tensorów wertykalnie (vstack) lub horyzontalnie (hstack)
- Squeeze - usuwa wymiar o rozmiarze '1'
- Unsqueeze - cofa usunięcie wymiaru o rozmiarze '1' (dodaje go na wskazaną pozycję)
- Permute - reorganizuje wymiary we wskazaną kolejność (prezentując widok)


In [73]:
import torch

tensor = torch.arange(1., 10.)
print(tensor, tensor.shape)


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


## Reshape

In [64]:
# Dodanie wymiaru do tensora
tensor_reshaped = tensor.reshape(1, 9)
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [65]:
# Dodanie wymiaru do tensora w inny sposób, ale tak aby suma elementów się zgadzała
tensor_reshaped = tensor.reshape(9, 1)
print(tensor_reshaped, tensor_reshaped.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


## View

In [72]:
# Zmiana widoku
view = tensor.view(1, 9)
print(view, view.shape)
# Wprowadzenie zamiany w view zmieni również tensor, ponieważ view jest widokiem tensora i dzielą te same dane
view[0, 0] = 5
print(tensor, view)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])


## Stack

In [75]:
# Stack przeprowadzony werkalnie
tensor_stacked = torch.stack((tensor, tensor, tensor), dim=0)
print(tensor_stacked, tensor_stacked.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([3, 9])


In [76]:
# Stack przeprowadzony horyzontalnie 
tensor_stacked = torch.stack((tensor, tensor, tensor), dim=1)
print(tensor_stacked, tensor_stacked.shape)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]]) torch.Size([9, 3])


## Squeeze i unsqueeze

In [78]:
# Squeeze
tensor = torch.arange(1., 10.)
tensor_reshaped = tensor.reshape(1, 9)
print(tensor_reshaped, tensor_reshaped.shape)
# Mamy tensor o rozmiarze (1, 9)

# Squeezed usunie wymiar o rozmiarze 1
tensor_squeezed = tensor_reshaped.squeeze()
print(tensor_squeezed, tensor_squeezed.shape)


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [80]:
# Unsqueeze
print(tensor_squeezed, tensor_squeezed.shape)
tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)
print(tensor_unsqueezed, tensor_unsqueezed.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


## Permute

In [86]:
orginal_tensor = torch.rand([224, 224, 3]) # symulujemy obraz o rozmiarze 224x224 i 3 kanałach (R, G, B)
print(orginal_tensor.shape)
# chcąc ustawić kanał kolorów na pierwszej pozycji, musimy użyć funkcji permute
permuted_tensor = orginal_tensor.permute(2, 0, 1) # Jako argumenty podajemy nową kolejność wymiarów
# 0>1 1>2 2>0
print(permuted_tensor.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [87]:
# Warto zaznaczyć, że oba tensory korzystają z tych samych danych, więc zmiana w jednym wpłynie na drugi
orginal_tensor[0, 0, 0] = 2137
print(orginal_tensor[0, 0, 0], permuted_tensor[0, 0, 0])

tensor(2137.) tensor(2137.)


# Ograniczenie losowości (reproducibility)

In [90]:
# Jeśli stworzymy dwa losowe tensory, to szansa że dane w nich zawarte będą takie same jest bardzo mała
import torch
tensor_1 = torch.rand([3, 3])
tensor_2 = torch.rand([3, 3])
print(tensor_1)
print(tensor_2)
# Sprawdzamy czy tensory są takie same
print(tensor_1 == tensor_2)

tensor([[0.4131, 0.7426, 0.3213],
        [0.8447, 0.0981, 0.5743],
        [0.7492, 0.1042, 0.0292]])
tensor([[0.5636, 0.7805, 0.8438],
        [0.2534, 0.7340, 0.8856],
        [0.0233, 0.2360, 0.4066]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [91]:
#Jeśli ustalimy seed do obliczania losowości
random_seed = 34

torch.manual_seed(random_seed)
tensor_3 = torch.rand([3, 3])

torch.manual_seed(random_seed)
tensor_4 = torch.rand([3, 3])

print(tensor_3)
print(tensor_4)

# Sprawdzamy czy tensory są takie same
print(tensor_3 == tensor_4)

tensor([[0.8718, 0.1155, 0.7057],
        [0.3841, 0.7322, 0.0119],
        [0.0205, 0.6273, 0.5561]])
tensor([[0.8718, 0.1155, 0.7057],
        [0.3841, 0.7322, 0.0119],
        [0.0205, 0.6273, 0.5561]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


Jest to przydatne jeśli chcemy coś odtworzyć. Np. ten sam plik na innym komputerze, a zależy nam na takich samych wynikach.